// Copyright (c) 2016 Lightricks. All rights reserved.
// Created by Alex Gershovich.

NS_ASSUME_NONNULL_BEGIN

/// Fake PaintCode module that does nothing. Similar in protocol to modules actually generated by
/// PaintCode.
@interface WFFakePaintCodeModule : NSObject
+ (void)drawImageAWithFrame:(CGRect)frame;
+ (void)drawImageBWithFrame:(CGRect)frame color:(UIColor *)color;
+ (void)drawImageCWithFrame:(CGRect)frame color:(UIColor *)color lineWidth:(CGFloat)lineWidth;
@end

NS_ASSUME_NONNULL_END
