// Copyright (c) 2015 Lightricks. All rights reserved.
// Created by Yaron Inger.

NS_ASSUME_NONNULL_BEGIN

@protocol PTNObject;

/// Photons error domain.
extern NSString * kPTNErrorDomain;

/// Key containing the URL associated with the error.
extern NSString * kPTNErrorRequestURLKey;

/// Key containing the Photons object associated with the error.
extern NSString * kPTNErrorAssociatedObjectKey;

/// Error codes that can be generated by Photons.
typedef NS_ENUM(NSInteger, PTNErrorCode) {
  PTNErrorCodeInvalidURL = 1,
  PTNErrorCodeAlbumNotFound = 2,
  PTNErrorCodeAssetNotFound = 3,
  PTNErrorCodeKeyAssetsNotFound = 4,
  PTNErrorCodeAssetLoadingFailed = 5,
  PTNErrorCodeInvalidAssetType = 6,
  PTNErrorCodeInvalidObject = 7
};

@interface NSError (Photons)

/// Caused when an invalid URL has been given.
+ (instancetype)ptn_invalidURL:(NSURL *)url;

/// Caused when the given album \c url has not been found.
+ (instancetype)ptn_albumNotFound:(NSURL *)url;

/// Caused when the given asset \c url has not been found.
+ (instancetype)ptn_assetNotFound:(NSURL *)url;

/// Caused when key assets for the album in the given \c url were not found.
+ (instancetype)ptn_keyAssetsNotFound:(NSURL *)url;

/// Caused when an asset identified by \c url has failed loading.
+ (instancetype)ptn_assetLoadingFailed:(NSURL *)url;

/// Caused when an asset identified by \c url has failed loading with the underlying \c error
/// providing more details about the failure reason.
+ (instancetype)ptn_assetLoadingFailed:(NSURL *)url underlyingError:(NSError *)error;

/// Caused when an asset with invalid type identified by \c url has been requested.
+ (instancetype)ptn_invalidAssetType:(NSURL *)url;

/// Caused when an invalid Photons object has been given.
+ (instancetype)ptn_invalidObject:(id<PTNObject>)object;

@end

NS_ASSUME_NONNULL_END
