// Copyright (c) 2015 Lightricks. All rights reserved.
// Created by Amit Goldstein.

NS_ASSUME_NONNULL_BEGIN

@class LTTextureArchiveType, LTTextureMetadata;

/// Metadata of an archive, generated by the \c LTTextureArchiver. Contains the metadata of the
/// texture and the type of archive.
@interface LTTextureArchiveMetadata : MTLModel <MTLJSONSerializing>

- (instancetype)init NS_UNAVAILABLE;

/// Initializes with the given archive \c type and texture \c metadata.
- (instancetype)initWithArchiveType:(LTTextureArchiveType *)type
                    textureMetadata:(LTTextureMetadata *)metadata;

/// Type of archive.
@property (readonly, nonatomic) LTTextureArchiveType *archiveType;

/// Metadata of the archived texture.
@property (readonly, nonatomic) LTTextureMetadata *textureMetadata;

@end

NS_ASSUME_NONNULL_END
