//
//  SPXDismissIcon.m
//  Enlight Ecosystem
//
//  Created by David on 17/12/2017.
//  Copyright © 2017 Lightricks ltd. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "SPXDismissIcon.h"


@implementation SPXDismissIcon

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawDismissIconWithFrame: (CGRect)frame color: (UIColor*)color
{
    //// Color Declarations
    UIColor* backgroundColor = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.7];

    //// Group 2
    {
        //// Rectangle Drawing


        //// Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 1, 28, 28)];
        [backgroundColor setFill];
        [ovalPath fill];


        //// Bezier Drawing
        UIBezierPath* bezierPath = [UIBezierPath bezierPath];
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 20.28, CGRectGetMinY(frame) + 11.7)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 20.28, CGRectGetMinY(frame) + 9.72) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 20.83, CGRectGetMinY(frame) + 11.15) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 20.83, CGRectGetMinY(frame) + 10.27)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 18.3, CGRectGetMinY(frame) + 9.72) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 19.73, CGRectGetMinY(frame) + 9.17) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 18.84, CGRectGetMinY(frame) + 9.18)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 15, CGRectGetMinY(frame) + 13.02)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 11.7, CGRectGetMinY(frame) + 9.72)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 9.72, CGRectGetMinY(frame) + 9.72) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 11.15, CGRectGetMinY(frame) + 9.17) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 10.27, CGRectGetMinY(frame) + 9.17)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 9.72, CGRectGetMinY(frame) + 11.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 9.17, CGRectGetMinY(frame) + 10.27) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 9.18, CGRectGetMinY(frame) + 11.15)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 13.02, CGRectGetMinY(frame) + 15)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 9.72, CGRectGetMinY(frame) + 18.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 9.72, CGRectGetMinY(frame) + 20.28) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 9.17, CGRectGetMinY(frame) + 18.85) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 9.17, CGRectGetMinY(frame) + 19.73)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 11.7, CGRectGetMinY(frame) + 20.28) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 10.27, CGRectGetMinY(frame) + 20.83) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 11.15, CGRectGetMinY(frame) + 20.83)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 15, CGRectGetMinY(frame) + 16.98)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 18.3, CGRectGetMinY(frame) + 20.28)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 20.28, CGRectGetMinY(frame) + 20.28) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 18.85, CGRectGetMinY(frame) + 20.83) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 19.73, CGRectGetMinY(frame) + 20.83)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 20.28, CGRectGetMinY(frame) + 18.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 20.83, CGRectGetMinY(frame) + 19.73) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 20.83, CGRectGetMinY(frame) + 18.84)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 16.98, CGRectGetMinY(frame) + 15)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 20.28, CGRectGetMinY(frame) + 11.7)];
        [bezierPath closePath];
        bezierPath.usesEvenOddFillRule = YES;
        [color setFill];
        [bezierPath fill];
    }
}

@end
