//
//  SPXDismissIcon.h
//  Enlight Ecosystem
//
//  Created by David on 17/12/2017.
//  Copyright © 2017 Lightricks ltd. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface SPXDismissIcon : NSObject

// Drawing Methods
+ (void)drawDismissIconWithFrame: (CGRect)frame color: (UIColor*)color;

@end
