// Copyright (c) 2014 Lightricks. All rights reserved.
// Created by Amit Goldstein.

@class LTPainterStrokeSegment, LTPainterPoint;
@protocol LTInterpolationRoutineFactory;

/// This class represents a painter stroke, used in the \c LTPainter mechanism.
/// The main purpose of this class is to generate interpolated points on the segment.
@interface LTPainterStroke : NSObject

/// Initializes a stroke with the given interpolation routine factory, starting at the given point.
/// The factory will be used to generate segments when new points are added to the stroke,
/// controlling the type of segments consisting the stroke.
- (instancetype)initWithInterpolationRoutineFactory:(id<LTInterpolationRoutineFactory>)factory
                                      startingPoint:(LTPainterPoint *)startingPoint;

/// Adds new segment connecting the last point to the given point.
/// Returns the new segment that was generated by this addition (which isn't necessarily the segment
/// from the last point to the new point, for some interpolation factories).
/// Returns \c nil if no segment is generated (again, for some interpolation routine types that
/// require a window).
- (LTPainterStrokeSegment *)addSegmentTo:(LTPainterPoint *)point;

/// Adds an unconnected point at the end of the stroke.
- (void)addPointAt:(LTPainterPoint *)point;

/// Starting point of the stroke.
@property (readonly, nonatomic) LTPainterPoint *startingPoint;

/// Array of either \c LTPainterStrokeSegment, or \c LTPainterPoint consisting the stroke.
/// Segment instances mark a segment connected from the previous point (or segment end) while point
/// instances mark a point not connected to its predecessor.
@property (readonly, nonatomic) NSArray *segments;

@end
